project:
  type: book
  output-dir: docs
  
book:
  title: "Metodologi Penelitian"
  subtitle: "Buku Panduan Praktis untuk Mahasiswa dan Peneliti Muda"
  reader-mode: true
  author: "Sunu Bagaskara"
  date: "9/8/2025"
  date-format: "D MMMM YYYY"
  sidebar:
    style: floating
    search: true
    collapse-level: 2
  language: id
          
  page-footer:
    left: |
      Metodologi Penelitian
    right: |
      Buku ini dicetak menggunakan <a href="https://quarto.org/">Quarto</a>.
  chapters:
    - index.qmd
    - part: 1_pengantar.qmd
      chapters: 
        - 1_1_ilmu.qmd
        - 1_2_hakikat.qmd
        - 1_4_literatur.qmd
        - 1_5_desain.qmd
        - 1_6_sampling.qmd
    - part: 2_pengantar.qmd
      chapters:
        - 2_10_pendekatan.qmd
    - part: 3_pengantar.qmd
      chapters: 
        - 3_17_proposalkuanti.qmd
        - 3_18_laporankuanti.qmd
    - part: 4_pengantar.qmd
      chapters: 
        - 4_19_paradigmakuali.qmd
        - 4_24_laporankuali.qmd
filters:
  # Run Quarto's default filters first
  - quarto
  - section-bibliographies
bibliography: references.bib
reference-section-title: References
csl: apa7id.csl

lang: id

crossref: 
  sec-prefix: "Bab"
  fig-prefix: "Gambar"
  tbl-prefix: "Tabel"
  eq-prefix: "Persamaan"
  
format:
  html:
    theme:
      - pandoc
    toc: true
    toc-depth: 4
    ##css: style.css
    number-sections: true
    nocite: false
  pdf:
    documentclass: scrreprt
    
  docx: 
    toc: false
    toc-depth: 3
    number-sections: true
    reference-doc: custom-reference.docx
    fontsize: 12pt
    linestretch: 1.5
  
editor: visual