project:
  type: book
  output-dir: docs
  
book:
  title: "Metodologi Penelitian"
  subtitle: "Buku Panduan Praktis untuk Mahasiswa dan Peneliti Muda"
  reader-mode: true
  author: "Sunu Bagaskara"
  date: "9/8/2025"
  date-format: "D MMMM YYYY"
  sidebar:
    style: docked
    search: true
    collapse-level: 1
  language: id
          
  page-footer:
    left: |
      Metodologi Penelitian
    right: |
      Buku ini dicetak menggunakan <a href="https://quarto.org/">Quarto</a>.
  chapters:
    - index.qmd
    - 1_1_ilmu.qmd
    - 1_2_hakikat.qmd
    - 1_4_literatur.qmd
    - 1_5_desain.qmd

filters:
  # Run Quarto's default filters first
  - quarto
  - section-bibliographies
bibliography: references.bib
reference-section-title: References
citeproc: true

lang: id

crossref: 
  sec-prefix: "Bab"
  fig-prefix: "Gambar"
  tbl-prefix: "Tabel"
  eq-prefix: "Persamaan"
  
format:
  html:
    theme:
      - pandoc
    toc: true
    toc-depth: 2
    ##css: style.css
    number-sections: true
    nocite: false
  pdf:
    documentclass: scrreprt
  
editor: visual